version: '3.6'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - database:/var/lib/mysql
    ports:
      - "3306:3306"
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root
      PMA_PASSWORD: root
  # mail:
  #   image: mailhog/mailhog:latest
  #   ports:
  #   - 8081:8025
#  www:
#    depends_on:
#    - db
##    environment:
##      DOCKER_ON_READY: "docker-php-ext-install mysqli"
##    command: bash -c "docker-php-ext-install mysqli"
#    # - mail
#    image: php:apache
#    volumes:
#    - "./code:/var/www/html"
#    ports:
#    - 8080:80

  www:
    depends_on:
      - db
#    image: php:apache
    build: "./"
    volumes:
      - "./code:/var/www/html"
    ports:
      - "8080:80"
    environment:
      BASE_DIR: /var/www/html/


volumes:
  database:
